workflows:
  ios-android-release:
    name: Build iOS & Android
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/*.ipa
